function showCDSBootstrapResults(datesCDS, spreadsCDS, ...
    survProbs_approx, int_approx, ...
    survProbs_exact, int_exact, ...
    survProbs_JT, int_JT)
%SHOWCDSBOOTSTRAPRESULTS Print and plot CDS bootstrap results.

    datesCDS = datesCDS(:);

    survProbs_approx = survProbs_approx(:);
    int_approx       = int_approx(:);
    survProbs_exact  = survProbs_exact(:);
    int_exact        = int_exact(:);
    survProbs_JT     = survProbs_JT(:);
    int_JT           = int_JT(:);

    n = numel(datesCDS);

    if numel(survProbs_approx) ~= n || numel(int_approx) ~= n || ...
       numel(survProbs_exact)  ~= n || numel(int_exact)  ~= n || ...
       numel(survProbs_JT)     ~= n || numel(int_JT)     ~= n
        error('All survival-probability and intensity vectors must have the same length as datesCDS.');
    end

    printCDSBootstrapReport(datesCDS, spreadsCDS, ...
        survProbs_approx, int_approx, ...
        survProbs_exact, int_exact, ...
        survProbs_JT, int_JT);

    plotCDSBootstrapResults(datesCDS, ...
        survProbs_approx, int_approx, ...
        survProbs_exact, int_exact, ...
        survProbs_JT, int_JT);
end